# Generated by Django 3.2.15 on 2022-10-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='адркс')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='дату запроса к геокодеру')),
            ],
            options={
                'verbose_name': 'место на карте',
                'verbose_name_plural': 'места на карте',
            },
        ),
    ]
