# Generated by Django 3.2.15 on 2022-10-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_status',
            field=models.CharField(choices=[('0', 'Необработанный'), ('1', 'Согласован с клиентом'), ('2', 'Собран'), ('3', 'Передан курьеру'), ('4', 'Выполнен')], default='0', max_length=15, verbose_name='статус'),
        ),
    ]
