# Generated by Django 3.2.15 on 2022-10-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_customer_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_status',
            field=models.CharField(choices=[('Необработан', 'Необработан'), ('Согласован', 'Согласован'), ('Собран', 'Собран'), ('Доставляется', 'Доставляется'), ('Выполнен', 'Выполнен')], db_index=True, default='Необработан', max_length=15, verbose_name='статус'),
        ),
    ]
