# Generated by Django 3.2.15 on 2022-10-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20221009_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
    ]
