# Generated by Django 3.2.15 on 2022-10-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_customer_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
    ]
