# Generated by Django 3.2.15 on 2022-10-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_customer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], db_index=True, max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
