# Generated by Django 3.2.15 on 2022-10-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_auto_20221019_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderelement',
            old_name='customer',
            new_name='order',
        ),
    ]
