# Generated by Django 3.2.15 on 2022-10-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата запроса к геокодеру'),
        ),
    ]
