# Generated by Django 3.2.15 on 2022-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='update_date',
        ),
        migrations.AddField(
            model_name='place',
            name='update_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата и время запроса к геокодеру'),
        ),
    ]
