# Generated by Django 3.2.15 on 2022-10-06 08:00

from django.db import migrations


def change_status(apps, schema_editor):
    Customer = apps.get_model('foodcartapp', 'Customer')
    for customer in Customer.objects.filter(order_status='Необработано'):
        customer.order_status = 'Необработан'
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20221006_1050'),
    ]

    operations = [
        migrations.RunPython(change_status),
    ]
