# Generated by Django 3.2.15 on 2022-10-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20221006_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий'),
        ),
    ]
