# Generated by Django 3.2.15 on 2022-10-06 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20221006_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='звонок совершен'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='доставлено'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='заказ создан'),
        ),
    ]
