# Generated by Django 3.2.15 on 2022-10-18 17:32

from django.db import migrations


def change_status(apps, schema_editor):
    Customer = apps.get_model('foodcartapp', 'Customer')
    for customer in Customer.objects.filter(order_status='Необработан'):
        customer.order_status = 'Не обработан'
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20221018_2030'),
    ]

    operations = [
        migrations.RunPython(change_status),
    ]
