# Generated by Django 3.2.15 on 2022-10-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_customer_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], db_index=True, max_length=15, null=True, verbose_name='Способ оплаты'),
        ),
    ]
